### ISSUE TITLE
Author archive page does not include co-authored posts

### ISSUE THREAD

**Issue by spiderbites** [Automattic/Co-Authors-Plus#594] opened 2018-08-24 03:41 UTC
Hello,

I'm finding that the author archive page only includes co-authored posts if the author is the first author added to the post.

Any help on this would be appreciated, thank you!

**Comment by TheCrowned** [comment] 2018-08-28 07:00
Hi there,
I have tried, but could not reproduce the issue. Can you please make sure that the issue occurs even with the latest commit from the master branch?

**Comment by spiderbites** [comment] 2018-08-29 03:04
Hello, I pulled the master branch and have the same issue. As far as I can tell the query which loads posts for the author just grabs posts for the given author id, so it doesn't include any posts for which the authors are secondary co-authors.

**Comment by TheCrowned** [comment] 2018-08-29 10:11
Thanks for trying that! Could you guide me in reproducing the issue, providing exact steps to follow to make the problem arise? Like, create a guest author/assign a post to it, visit what page, etc... :)

**Comment by spiderbites** [comment] 2018-09-06 03:36
I think I've identified the issue as coming from a theme I'm using where `$post_type` is set to `any` on the author archive page. Not sure how this is causing the issue but setting the `$post_type` to `post` resolves the issue.

**Comment by alexiskulash** [comment] 2018-09-17 13:47
Thanks for letting us know! I'll go ahead and close this issue out as it's no longer a reported bug with the plugin.

**Closed by alexiskulash** 2018-09-17 13:47 UTC
