### ISSUE TITLE
Author autocomplete not working for new posts

### ISSUE THREAD

**Issue by pabamato** [Automattic/Co-Authors-Plus#802] opened 2021-06-10 21:09 UTC
Autocomplete ajax request is not returning any data for new posts or posts without a previously co-author set.
I believe this is related to the following changes added on 3.4.7:
- https://github.com/Automattic/Co-Authors-Plus/blob/master/co-authors-plus.php#L1200 
- https://github.com/Automattic/Co-Authors-Plus/commit/c51143e9d332d3818e4641c5dd6de79fd314a308

**Working example:**
Steps to reproduce, create a new post using v3.4.5 and assign an author using the autosuggest.
Upgrade to v3.4.7 and try to add a new author.
https://take.ms/epeEu

**Non Working example:**
Create a new post and try to assign an author via autosuggest
https://take.ms/YH9Zr

**Comment by rebeccahum** [comment] 2021-06-11 17:37
This seems to be a duplicate of #799. @nielslange can you look into this?

**Comment by nielslange** [comment] 2021-06-14 10:39
This issue sounds identical to #799, @rebeccahum. 

@pabamato Thanks for reporting this problem. I'll close this ticket for now, so that we can proceed in #799. I also created the PR #803 to resolve this problem. Feel free to test if that PR solves the problem on your end.

**Closed** 2021-06-15 08:59 UTC
