### ISSUE TITLE
Allow bulk edit - change author

### ISSUE THREAD

**Issue by eecoston** [Automattic/Co-Authors-Plus#819] opened 2021-09-08 00:11 UTC
Enable bulk change author when Co Authors plus is active (this would be helpful to transition sites to use co authors plus for users who have a lot of posts, instead of manually changing each one)

This is what the bulk edit box looks like when co-authors plus is active, no author box:
![image](https://user-images.githubusercontent.com/69772473/132425413-7a33d7a9-51ea-47ac-b098-8da6cb7c283b.png)

**Comment by rebeccahum** [comment] 2021-09-09 16:19
Duplicate of #551

**Closed by rebeccahum** 2021-09-09 16:19 UTC
Labels: enhancement
