### ISSUE TITLE
SQL Error from Regex in WHERE Clause

### ISSUE THREAD

**Issue by scofennell** [Automattic/Co-Authors-Plus#592] opened 2018-08-21 18:34 UTC
There seems to be an issue with the regex that filters the WHERE clause on the front end:

`SELECT SQL_CALC_FOUND_ROWS wp_posts.ID
FROM wp_posts
LEFT JOIN wp_term_relationships AS tr1
ON (wp_posts.ID = tr1.object_id)
LEFT JOIN wp_term_taxonomy
ON ( tr1.term_taxonomy_id = wp_term_taxonomy.term_taxonomy_id )
WHERE 1=1
AND ((wp_term_taxonomy.taxonomy = 'author'
AND wp_term_taxonomy.term_id = '78'826
OR (wp_term_taxonomy.taxonomy = 'author'
AND wp_term_taxonomy.term_id = '20988')))
AND wp_posts.post_type = 'post'
AND (wp_posts.post_status = 'publish'
OR wp_posts.post_status = 'private')
GROUP BY wp_posts.ID
HAVING MAX( IF ( wp_term_taxonomy.taxonomy = 'author', IF ( wp_term_taxonomy.term_id = '20988'
OR wp_term_taxonomy.term_id = '78',2,1 ),0 ) ) <> 1
ORDER BY wp_posts.post_date DESC
LIMIT 0, 10 /* From [www.lexblog.com/author/catherinelawson/] in [/nas/content/live/lexblognetwork/index.php:17] */`

`You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '826 OR (wp_term_taxonomy.taxonomy = 'author' AND wp_term_taxonomy.term_id = '209' at line 1`

This issue is also documented here, with a suggested fix:  https://wordpress.org/support/topic/regexp-in-plugin-creates-syntax-errors-in-sql-queries/

See PR:  https://github.com/Automattic/Co-Authors-Plus/pull/593

<img width="1680" alt="screen shot 2018-08-21 at 2 33 19 pm" src="https://user-images.githubusercontent.com/1585637/44421706-5745ed00-a54f-11e8-894a-5e4d1cc2d264.png">

**Comment by TheCrowned** [comment] 2018-08-27 07:02
Duplicate of #573.

**Closed** 2018-10-24 02:00 UTC
