### ISSUE TITLE
Replace wp_die errors with WordPress UI error messages.

### ISSUE THREAD

**Issue by ryanmarkel** [Automattic/Co-Authors-Plus#227] opened 2014-10-02 13:35 UTC
Most error messages in CAP are presented through stark wp_die screens and often those error messages can be somewhat cryptic. When possible, CAP should display error messages in the standard UI style, providing non-vague explanations as to why something can't be done.

**Comment by GaryJones** [comment] 2023-07-22 21:50
Since this is a very general Issue, lacking specific examples, and it's getting on for nine years old, I will close it out. New issues that reference specific examples, and how to reproduce those error messages, would be accepted.

**Closed by GaryJones** 2023-07-22 21:50 UTC
Labels: Type: enhancement, Priority: medium

**Comment by EarthlingDavey** [comment] 2024-10-17 15:45
Here in 2024 👋  see you in another 10 years
