### ISSUE TITLE
Plugin Preventing Correct Listing of Pages When Selecting "Mine" Link

### ISSUE THREAD

**Issue by catchmyfame** [Automattic/Co-Authors-Plus#508] opened 2018-04-23 16:23 UTC
The issue is that when you visit the Pages section of WP and click the "Mine" link, the full list of pages belonging to the logged in user isn't shown. From what I'm seeing, only pages marked as Private are being listed. However, if you instead select the "All" link, and the pick the same user from the "All users" dropdown menu and then click the Filter button, the proper listing is displayed.

The "Mine" link is something like 

`example.com/wp-admin/edit.php?post_type=page&author=25` or `example.com/wp-admin/edit.php?post_type=page`

And is the same regardless of whether the CAP is enabled or disabled, so something in the plugin is preventing the proper listing. 

When I disable the CAP plugin this issue goes away, and when I enable it it returns. I have disabled all other plugins and confirmed that it's CAP that is causing the issue.

**Comment by catchmyfame** [comment] 2018-04-24 20:04
So far I've tracked the problem down to being in co-authors-plus.php

**Comment by catchmyfame** [comment] 2018-04-25 14:05
Upon further investigation it appears as if the change in SQL in the `posts_join_filter` function in  co-authors-plus.php file is causing the issue. The difference in the rendered code:

**NEW** (buggy):

```
LEFT JOIN wordpress_cms_term_relationships 
AS tr1 
ON (wordpress_cms_posts.ID = tr1.object_id) 
LEFT JOIN wordpress_cms_term_taxonomy 
ON ( tr1.term_taxonomy_id = wordpress_cms_term_taxonomy.term_taxonomy_id )
```

**OLD** (working):

```
LEFT JOIN wordpress_cms_term_relationships 
ON (wordpress_cms_posts.ID = wordpress_cms_term_relationships.object_id) 
LEFT JOIN wordpress_cms_term_relationships 
AS tr1 
ON (wordpress_cms_posts.ID = tr1.object_id) 
LEFT JOIN wordpress_cms_term_taxonomy 
ON ( tr1.term_taxonomy_id = wordpress_cms_term_taxonomy.term_taxonomy_id )
```

For testing purposes, if I replace the changed new SQL with the 3.2.2 version the problem goes away.

**Comment by combs** [comment] 2018-05-11 19:37
We are seeing this at washingtonian.com too -- would love to see a fix.

**Comment by dartiss** [comment] 2018-06-20 14:44
Heavy.com are also seeing the same issue.

They have the following filter in place for database performance issues, and it's been found that removing this temporarily fixes the user posts issue...

`add_filter( 'coauthors_plus_should_query_post_author', '__return_false' );`

However, I would not recommend removing this on any production sites, as the consequences of the performance problem is much greater than how user posts are listed.

(Ticket for internal use - #79174-z)

**Comment by sboisvert** [comment] 2018-07-24 19:31
@smistephen Would you mind taking a look?

**Comment by smistephen** [comment] 2018-07-25 17:09
Current state of play on this issue:

I replicated the issue, and believe I've tracked down (part of) the cause.

Turning on the query log, I found that it was running _takes deep breath_

```
SELECT SQL_CALC_FOUND_ROWS wp_posts.ID
FROM wp_posts
LEFT JOIN wp_term_relationships AS tr1 ON (wp_posts.ID = tr1.object_id)
LEFT JOIN wp_term_taxonomy ON ( tr1.term_taxonomy_id = wp_term_taxonomy.term_taxonomy_id )
WHERE 1=1
AND (
    wp_posts.post_author IN (3)
    AND wp_posts.post_type = 'post'
    AND (
        wp_posts.post_status = 'publish'
        OR wp_posts.post_status = 'future'
        OR wp_posts.post_status = 'draft'
        OR wp_posts.post_status = 'pending'
        OR wp_posts.post_author = 3
        OR (
            wp_term_taxonomy.taxonomy = 'author'
            AND wp_term_taxonomy.term_id = '8'
        )
    )
    AND wp_posts.post_status = 'private'
)
GROUP BY wp_posts.ID
HAVING MAX(
    IF (
        wp_term_taxonomy.taxonomy = 'author',
        IF ( 
            wp_term_taxonomy.term_id = '8',2,1
        ),0 
    )
) <> 1
ORDER BY wp_posts.post_date DESC
LIMIT 0, 20
```

I realize that's a honker of a query. Let's focus on the relevant part:

```
AND (
    wp_posts.post_author IN (3)
    AND wp_posts.post_type = 'post'
    AND (
        wp_posts.post_status = 'publish'
        OR wp_posts.post_status = 'future'
        OR wp_posts.post_status = 'draft'
        OR wp_posts.post_status = 'pending'
        OR wp_posts.post_author = 3
        OR (
            wp_term_taxonomy.taxonomy = 'author'
            AND wp_term_taxonomy.term_id = '8'
        )
    )
    AND wp_posts.post_status = 'private'
)
```

See that last line? `AND wp_posts.post_status = 'private'`? Yeah, that somehow got bumped all the way down there. I assume it's supposed to be up with the rest of the post statuses?

Changing that part of the query to:

```
AND (
    wp_posts.post_author IN (3)
    AND wp_posts.post_type = 'post'
    AND (
        wp_posts.post_status = 'publish'
        OR wp_posts.post_status = 'future'
        OR wp_posts.post_status = 'draft'
        OR wp_posts.post_status = 'pending'
        OR wp_posts.post_status = 'private'
        OR wp_posts.post_author = 3
        OR (
            wp_term_taxonomy.taxonomy = 'author'
            AND wp_term_taxonomy.term_id = '8'
        )
    )
)
```

and manually running it against the database produced expected results.

Now I just need to figure out where the error is being introduced.

It's hooked on to the `posts_where` hook, takes in two arguments, `$where` and `$query`, the former being what we're interested in and the latter being the WP_Query object itself.

Setting a breakpoint at https://github.com/Automattic/Co-Authors-Plus/blob/master/co-authors-plus.php#L657 and dumping the value of `$where` provides the following:

```
" AND wp_posts.post_author IN (3)  AND wp_posts.post_type = 'post' AND (wp_posts.post_status = 'publish' OR wp_posts.post_status = 'future' OR wp_posts.post_status = 'draft' OR wp_posts.post_status = 'pending' OR wp_posts.post_author = 3 AND wp_posts.post_status = 'private')"
```
Yep, that's the exact same thing, just formatted less nicely.

So it must be happening somewhere upstream.

Where? That's my next task, this comment is long enough.

**Comment by TheCrowned** [comment] 2018-07-25 17:50
Hey! I am debugging a similar issue where the Mine view does not display as expected (I think #555), and I think you may want to look at lines 718 and 734. The idea is that CAP replaces the user ID in the query with the user ID + terms IDs. Just a high level thought since we are working on similar things :)

**Comment by smistephen** [comment] 2018-07-26 12:49
@TheCrowned you were on the right track, it's line 715:

`$where = preg_replace( '/\s\b(?:' . $wpdb->posts . '\.)?post_author\s*IN\s*(.*' . $id . '.)/', ' (' . $maybe_both_query . ' ' . $terms_implode . ')', $where, -1 ); #' . $wpdb->postmeta . '.meta_id IS NOT NULL AND`

Now to figure out how to fix this.

**Comment by smistephen** [comment] 2018-07-26 13:12
Got it.

The previous regex looked for

`\s\b(?:wp_posts\.)?post_author\s*IN\s*(.*1023.)`

within

`AND wp_posts.post_author IN (1023)  AND wp_posts.post_type = 'post' AND (wp_posts.post_status = 'publish' OR wp_posts.post_status = 'future' OR wp_posts.post_status = 'draft' OR wp_posts.post_status = 'pending' OR wp_posts.post_author = 1023 AND wp_posts.post_status = 'private')`

which chopped off the last bit, it didn't match `AND wp_posts.post_status = 'private')`, so the query was broken by inserting some stuff in between those two parts.

Changing the regex to

`\s\b(?:wp_posts\.)?post_author\s*IN\s*(.*private'.)`

swaps out the string that signifies the end of the relevant portion from `1023 ` to `private`, restoring normal functionality.

Now to test this doesn't break anything else.

**Comment by phylaxis** [comment] 2018-09-28 23:37
I just tried to use the 1c88a82 patch in my testing environment to see if it would resolve this issue on a custom post type I have. I was unable to get it to work. Is this fix only for the standard Wordpress "post" types?

**Comment by jtbayly** [comment] 2018-11-05 20:33
I'm not sure whether it's only standard post types, but I can confirm that it does work with standard posts.

**Comment by catchmyfame** [comment] 2019-04-08 18:44
We're approaching the one year mark on this bug. Any hope of a fix?

**Comment by rebeccahum** [comment] 2019-04-08 18:45
@catchmyfame Hi!  We're just in the phase of testing out a fix for it that will go out in the next release.

**Comment by rebeccahum** [comment] 2019-05-01 12:38
Closing per #662.

**Closed by rebeccahum** 2019-05-01 12:38 UTC

**Comment by jxxe** [comment] 2020-05-03 08:05
> We are seeing this at washingtonian.com too -- would love to see a fix.

@combs Did you ever find a solution for this?

**Comment by combs** [comment] 2020-05-06 18:55
> > We are seeing this at washingtonian.com too -- would love to see a fix.
> 
> @combs Did you ever find a solution for this?

my understanding is that it was fixed in #663 but I no longer have need to use this software

**Comment by rebeccahum** [comment] 2020-05-11 18:04
@jxxe This should be fixed now, are you still experiencing this issue?

**Comment by jxxe** [comment] 2020-05-11 18:09
@rebeccahum Not exactly this. Some authors are attached to a post, but it doesn't show up when you view their profile. The post only shows up if it is saved after the Co-Authors Plus plugin was activated. For example, [here](https://berkeleyhighjacket.com/?s=Amaya+Polanco+Zimmerman) are the search results for an author, and [here's](https://berkeleyhighjacket.com/author/amayapolancozimmerman/) the author's profile page.

**Comment by sboisvert** [comment] 2020-05-11 18:53
@jxxe There are 2 ways to solve the problem. 
1) The better long term solution is to backfill all the co-authors for all the posts. You can run the CLI command https://github.com/Automattic/Co-Authors-Plus/blob/master/php/class-wp-cli.php#L53
by doing `wp --url=example.com co-authors-plus create-terms-for-posts` to achieve this.
Note that this assumes that [WP-CLI](https://wp-cli.org/) is installed.
Depending on the size of your site, that query can take quite a while (should be fine if you have less than 100 authors and/or less than 100 000 posts)
While this will take more time upfront, it will ensure that your day to day site queries are faster.
2) A quick fix, that makes the day to day of the site slower and should be avoided if possible is to add `add_filter( 'coauthors_plus_should_query_post_author', '__return_true' );`
This will create an extra join for every author query. This means even if a post doesn't have a co-author, it will be found using the original author. Again, this would be a sub-optimal solution and I'd recommend method number 1.
Hope this helps!

**Comment by jxxe** [comment] 2020-05-11 19:53
@sboisvert I get this error: ```Error: 'co-authors-plus' is not a registered wp command.```

**Comment by sboisvert** [comment] 2020-05-11 20:27
>How slow is the second option? Is there a way to achieve the first option without needing access to SSH? Right now I need to contact my host to run the command for me because they don't provide access to SSH.

It's best to test it yourself on your site as it's influenced by the size of your site, the amount of traffic and the host you have. If you have less than 100 000 posts you'll probably be fine :)

>I get this error: Error: 'co-authors-plus' is not a registered wp command.

Do you have a multisite? if so, was the right site specified with the --url= parameter?
What do you get when you run the `wp plugin list --url=www.example.com` command? If co-authors isn't in that list, you should confirm that it's enabled on the site and that you see your other plugins.
If you don't see it, you might want to check what site this is being run on. When you run the `wp option get siteurl --url=www.example.com` command, is that your site's url that's coming back to you?

**Comment by jxxe** [comment] 2020-05-11 20:45
@sboisvert Ok, I added the second option to my `functions.php` file and it's not working. Am I missing something?

**Comment by sboisvert** [comment] 2020-05-11 20:50
If the second option doesn't work I'd try again with the first one with the help of your host.

**Comment by jxxe** [comment] 2020-05-11 21:12
@sboisvert I haven't tested this, but is there any reason why I shouldn't do this, or why it wouldn't work? I have less than 1,500 posts.
```php
function cap_fixer() {
	$args = array(
		'order'            => 'ASC',
		'orderby'          => 'ID',
		'post_type'         => 'post',
		'posts_per_page'    => -1,
		'update_meta_cache' => false,
	);
	$posts = new WP_Query( $args );

    foreach ( $posts->posts as $single_post ) {
		if(empty(cap_get_coauthor_terms_for_post($post->ID) {

			$author = (! empty( $authors[ $single_post->post_author ] ) ) ? $authors[ $single_post->post_author ] : get_user_by( 'id', $single_post->post_author );
			$authors[ $single_post->post_author ] = $author;

			$author_term = ( ! empty( $author_terms[ $single_post->post_author ] ) ) ? $author_terms[ $single_post->post_author ] : $coauthors_plus->update_author_term( $author );
			$author_terms[ $single_post->post_author ] = $author_term;

			wp_set_post_terms( $single_post->ID, array( $author_term->slug ), $coauthors_plus->coauthor_taxonomy );

		}
	}
}
add_action('init','cap_fixer');
```

**Comment by jxxe** [comment] 2020-06-13 21:12
I finally got access to SSH and installed WP-CLI, but I'm getting this error. WP-CLI is installed in a folder in the home directory called `wp`, WordPress is in the `public_html` directory.

The error:
```
$ wp --url=`berkeleyhighjacket.com` co-authors-plus create-terms-for-posts
bash: berkeleyhighjacket.com: command not found
Warning: No WordPress installation found. If the command 'co-authors-plus create-terms-for-posts' is in a plugin or theme, pass --path=`path/to/wordpress`.
Error: 'co-authors-plus' is not a registered wp command. See 'wp help' for available commands.
```
