### ISSUE TITLE
Gravatar image URL in author page previews

### ISSUE THREAD

**Issue by tmmbecker** [Automattic/Co-Authors-Plus#783] opened 2021-04-20 15:03 UTC
When previewing an author page for a Guest Author, the preview displays as a placeholder because it appears to be using the `og:image` tag, which pulls the Gravatar URL by default. Here's an example of what the preview looks like when the author URL is shared in Slack:

![Screen Shot 2021-04-20 at 11 01 05](https://user-images.githubusercontent.com/22805865/115418799-c4f6bb00-a1c7-11eb-9182-ac0d0dab9d91.png)

Can we update the author pages to use the correct avatar?

**Comment by nielslange** [comment] 2021-04-21 06:13
Hello @tmmbecker, thanks for reporting this. I looked up this case on a fresh installation using WordPress 5.7.1 and Co-Authors Plus 3.4.5, but I do not see an `og:image` tag on the site. I tested this with various default themes.

Can you tell me what theme you are using and if you're using a plugin that is adding the `og:image` tag, such as [Yoast SEO](https://wordpress.org/plugins/wordpress-seo/) or [All in One SEO](https://wordpress.org/plugins/all-in-one-seo-pack/)?

**Comment by tmmbecker** [comment] 2021-04-27 22:04
@nielslange this is a Newspack site so the themes are all Newspack-specific. We use Yoast for tags on most sites.

**Comment by nielslange** [comment] 2021-05-05 06:58
Thanks for sharing the example, @tmmbecker. 

**Steps to reproduce**

1. Go to https://prismreports.org/author/ashton-lattimore/ and copy URL
2. Go to https://www.opengraph.xyz/, paste URL and click "Check website"
3. The author image is not visible
4. Go to https://nielslange.blog/about/ and copy URL
5. Go to https://www.opengraph.xyz/, paste URL and click "Check website"
6. The author image is visible

**Potential solution**

Add author image as [`og:image`](https://ogp.me/), if author image is available.

**Comment by rebeccahum** [comment] 2021-05-05 14:54
@nielslange Have you been able to reproduce this on a local install?

**Comment by nielslange** [comment] 2021-05-06 14:32
> @nielslange Have you been able to reproduce this on a local install?

I haven't, as I could not imagine that it's possible to test this bug locally as Slack cannot access my local site and therefore no author image will be visible.

That said, I just tried reproducing this bug locally, and as expected, the URL of my local environment cannot be resolved by Slack.

**Comment by rebeccahum** [comment] 2021-05-06 14:36
Sorry, just to clarify what I meant by locally I meant on an isolated public test blog where the author image is not visible.

**Comment by nielslange** [comment] 2021-05-07 14:14
> Sorry, just to clarify what I meant by locally I meant on an isolated public test blog where the author image is not visible.

@rebeccahum I tested this problem isolated, but also noticed that the author image does not appear independent if the CAP plugin is active or not. 

@tmmbecker This problem is not related to this plugin as the author image also does not appear when the plugin is deactivated and/or not installed. I looked up your example site https://prismreports.org/author/ashton-lattimore/ again and see that there's an Open Graph link for the Gravatar that points to https://secure.gravatar.com/avatar/d183f5bc2eebfab706035d923ab6fbc3?s=500&amp;d=mm&amp;r=g. I suggest that you contact the Slack support to clarify why another image appears in Slack and that you contact the Yoast support to clarify why the Gravatar placeholder image had been added instead of the correct author image.

As this problem is not caused by this plugin, I'm going to close this issue for now.

**Comment by tmmbecker** [comment] 2021-05-21 19:26
Thanks for the deep dive here @nielslange and I apologize for the delay in following up. We actually [pushed a patch](https://github.com/Automattic/newspack-plugin/pull/947) to fix this for Newspack sites. But the bug is related to the [CAP's integration with Yoast's new Schema API](https://github.com/Automattic/Co-Authors-Plus/issues/710).

**Comment by nielslange** [comment] 2021-05-28 13:42
Thanks for clarifying this, @tmmbecker. As the bug is related to https://github.com/Automattic/Co-Authors-Plus/issues/710, I'd keep this issue closed and address this problem in the already created issue.

**Closed** 2021-05-28 13:42 UTC
Labels: Priority::Medium, confirmed-bug
