### ISSUE TITLE
CoAuthors Integration - 404 Error for not mapped users

### ISSUE THREAD

**Issue by mcrapanzano** [Automattic/Co-Authors-Plus#409] opened 2017-03-30 09:11 UTC
Hi, 
I'm new to this repository, I'm using coauthors plus on a website and I really like it, but I have some difficulties in integrating it. Documentation provided is not really clear for me.
This is the issue I'm having after integrating it in a theme: 
http://diritticomparati.themmc.it/author/alice-minisini
If I connect a guest author to a user, the page works,
If I don't map the guest author as user, I get a 404 error.
Could you help me to solve this please?
Thanks,
Monica

**Comment by andrewteg** [comment] 2017-05-14 18:19
We are having this same issue using the X theme. Did you ever hear anything on this?

**Comment by rebeccahum** [comment] 2017-05-30 19:18
@mcrapanzano @andrewteg Hi guys, can you please describe the steps you took to integrate it into a theme?

**Comment by rebeccahum** [comment] 2017-05-30 19:23
@mcrapanzano @andrewteg Hi, have you reviewed [this documentation](https://vip.wordpress.com/documentation/incorporate-co-authors-plus-template-tags-into-your-theme/) to ensure you have integrated the plugin into your theme?

**Comment by rebeccahum** [comment] 2017-05-30 19:25
@mcrapanzano @andrewteg Hi, have you reviewed [this documentation](https://vip.wordpress.com/documentation/incorporate-co-authors-plus-template-tags-into-your-theme/) to ensure you have integrated the plugin into your theme?

**Comment by andrewteg** [comment] 2017-05-31 15:33
Thanks for following up. I've read over the docs again and believe I have isolated the problem for us so it may or may not be what @mcrapanzano is seeing.

For us I think a more appropriate description is "404 Guest Author Profiles" perhaps. It seems that until a user has an actual post assigned to them, they get a 404 for their Author Profile. This seems like a bug but perhaps it is by design?  I just installed the plugin on a test site and disabled all other plugins and created a guest author, and he is 404 at http://andrewteg.com/wp?author_name=andrew-one ... the same thing happened to http://andrewteg.com/wp?author_name=andrew-two until I assigned him a Hello World post, and now he is fine.

The reason this wasn't apparent to us is that the counts are all off our our Guest Authors screen. Is there a function to reset that or a way to clear cache so it re-calculates those post counts?

Thanks!

**Comment by rebeccahum** [comment] 2017-06-01 18:55
@andrewteg It is actually by design where if a guest author does not have any posts, it will not display any posts.  Thank you for narrowing down where the 404 issue is coming from.  

To update your post counts, run the wp-cli command `wp co-authors-plus update-author-terms` and that should do the trick.

**Comment by philipjohn** [comment] 2017-06-17 16:24
I'm going to close this in favour of #425 which says we need to change the plugin behaviour to align with core.

**Closed by philipjohn** 2017-06-17 16:24 UTC
