### ISSUE TITLE
Merge Guest Author with same-slug WP Admin User

### ISSUE THREAD

**Issue by tmmbecker** [Automattic/Co-Authors-Plus#782] opened 2021-04-19 15:31 UTC
If a Guest Author has the same slug as a WP Admin user account, it's not possible to merge or to update the Guest Author profile. CAP should allow merging with WP Admin users that have the same slug. 

Deleting the Guest Author only allows for reassigning to another Guest Author. As part of this fix, let's also allow for reassigning to WP Admin users.

**Comment by rebeccahum** [comment] 2021-04-20 12:17
Closing as duplicate of #578.

**Closed by rebeccahum** 2021-04-20 12:17 UTC
