### ISSUE TITLE
Problem with query on wordpress 4.6.1

### ISSUE THREAD

**Issue by RoccoMarco** [Automattic/Co-Authors-Plus#379] opened 2016-10-22 09:24 UTC
Dear all,
I have read on the web about this issue and it seems I am not the one experimenting this issue.

I was working with the latest version of co-author plus (3.2.1) experimenting this issue: making a query of post count related to an author the result is 0!

Query based on author doesn't include coauthor results... I have take a look to bug #374 and updated the plugin to the development version. Problem still unsolved...

**Comment by mjangda** [comment] 2016-11-08 18:04
> I was working with the latest version of co-author plus (3.2.1) experimenting this issue: making a query of post count related to an author the result is 0!

I'm not sure I understand. Can you share the code you're using to do the query?

**Comment by trepmal** [comment] 2016-11-11 18:16
Hi @RoccoMarco, I just wanted to follow up on @mjangda's request. Would you be able to share the code you're using for the query?

**Comment by RoccoMarco** [comment] 2016-11-15 22:22
```
    $args = array(
      'author'  => $authID,
      'posts_per_page' => 50,
      'post_type' => 'post',
      'post_status' => 'publish'
    );
    query_posts($args);

    echo '<ul class="post-list">';
    // Start the Loop.
    while ( have_posts() ) : the_post();
      echo  '<li><h3><a class="title-link" href="'.get_the_permalink().'">'.get_the_title().'</a></h3></li>';
    // End the loop.
    endwhile;
    echo  '</ul>';
```
This return should return a list of article related to the author identified by $authID.  It seems like list misses all the articles coauthored by $authID. An article appear in the list only when author is the "first" author of it.

**Comment by trepmal** [comment] 2016-11-17 17:44
Hi @RoccoMarco, thanks for the info.

The query is not going to work as expected with the `author` argument. There's a deeper issue here with how Co-Authors Plus intercepts the query to include additional authors (https://github.com/Automattic/Co-Authors-Plus/issues/374#issuecomment-244481374).

For your case, try to use `author_name` instead.

_(As a separate note: in most cases [`query_posts()` is not what you want](https://developer.wordpress.org/reference/functions/query_posts/))_

**Comment by RoccoMarco** [comment] 2016-11-17 19:52
Actually I have already tested this path. Using 
author_name => nicename
result is all posts from every author. Maybe I am missing something.

**Comment by trepmal** [comment] 2016-11-21 22:53
So far I've been unable to reproduce the behavior you're describing.

Here's the code I'm using to run some tests:

```
$args = array(
	'author_name' => 'guest-author',
);
$nq = new WP_Query( $args );

echo '<pre>';
var_dump( $nq->request );
echo '</pre>';

echo '<ul class="post-list">';
while ( $nq->have_posts() ) : $nq->the_post();
	echo  '<li><h3><a class="title-link" href="'.get_the_permalink().'">'.get_the_title().'</a></h3></li>';
endwhile;
wp_reset_postdata();
echo  '</ul>';
```

In my test site, `guest-author` is mapped to a real user. I've also used an unmapped real user, and an unmapped guest author, all of which have produced the expected results.
Additionally, each have at least one post where they are the only author, and another where they are a coauthor.

If you haven't already, are you able to deactivate any other plugins you are using and switch to the default theme? This could help narrow down any conflicts.

**Comment by trepmal** [comment] 2016-11-21 23:04
@RoccoMarco You also commented on #374, would you be able to test the pending fix #381 (it's not a big change if you need to apply it manually) and see if it resolves your issue? 
Perhaps another plugin is adding a `tax_query` automatically?

**Comment by RoccoMarco** [comment] 2016-11-22 15:18
Pending fix doesn't solve my issue. Thanks a lot for your interest and help.

**Comment by trepmal** [comment] 2016-11-22 17:24
> Edit: pending fix solve my issue if I use user_nicename instead of user_ID

This sounds promising. Can you confirm if any of your active plugins or theme is adding a `tax_query` automatically? That will be helpful in determining if this issue is the same as #374

**Comment by RoccoMarco** [comment] 2016-11-22 20:12
Hard to tell. How can I get this information?

**Comment by trepmal** [comment] 2016-11-25 21:11
Could be, I don't have any experience with that plugin.

If you were to undo the patch and deactivate Polylang, do you still have the reported problem?

If that doesn't do it, I'd again start with removing the patch/pending fix and deactivating all plugins. Then reactivate one-by-one and see if the issue returns. When/if it returns, that'll narrow down which plugin is in the way.

**Comment by RoccoMarco** [comment] 2016-11-25 21:14
I am sorry but right now I cannot disable the plugin. I have to put website in maintenance mode to do this risking to screwed up everything.

 I will made a local copy to do accurate tests in the weekend.

**Comment by trepmal** [comment] 2016-11-25 21:18
No problem, and no rush. Enjoy your weekend :)

**Comment by philipjohn** [comment] 2017-01-15 18:37
Hi @RoccoMarco did you get any time to take a look at this?

**Comment by RoccoMarco** [comment] 2017-01-15 18:41
Actually I have forgotten it :( . I will make some tests but right now I have not enought spare time.

**Comment by GaryJones** [comment] 2023-07-22 21:46
I'll close this out on the assumption that we've all moved on from WP 4.6.1 and CAP 3.2.1, but if the problem still exists, please open a new Issue.

**Closed by GaryJones** 2023-07-22 21:46 UTC
Labels: Status: needs investigation, Status: awaiting reporter feedback
