### ISSUE TITLE
SQL Query Error (Regex)

### ISSUE THREAD

**Issue by strang3** [Automattic/Co-Authors-Plus#595] opened 2018-08-24 09:04 UTC
The SQL Error shows up when:
- Backend: Show posts from selected user
- Frontend: When on Author page (only when logged in)

Plugin Version: 3.3.0
The error only shows up, because the user id gets replaced wrong.
Ex.:
login user id: 2
selected user id: 24
Wrong Query Part: 'AND wp_term_taxonomy.term_id = '768'4'
(The user id only gets replaces partially.)

I have made a quick fix:
Line 725 - 731:
```
$current_coauthor      = $this->get_coauthor_by( 'user_nicename', wp_get_current_user()->user_nicename );
					$current_coauthor_term = $this->get_author_term( $current_coauthor );
					
					$current_user_query  = $wpdb->term_taxonomy . '.taxonomy = \''. $this->coauthor_taxonomy.'\' AND '. $wpdb->term_taxonomy .'.term_id = \''. $current_coauthor_term->term_id .'\'';
					$this->having_terms .= ' ' . $wpdb->term_taxonomy .'.term_id = \''. $current_coauthor_term->term_id .'\' OR ';
					
					$where = preg_replace( '/(\b(?:' . $wpdb->posts . '\.)?post_author\s*=\s*(' . get_current_user_id() . '))/', $current_user_query, $where, -1 ); #' . $wpdb->postmeta . '.meta_id IS NOT NULL AND
```

fixed:
```
$current_coauthor      = $this->get_coauthor_by( 'user_nicename', wp_get_current_user()->user_nicename );
					$current_coauthor_term = $this->get_author_term( $current_coauthor );

					$current_user_query  = $wpdb->term_taxonomy . '.taxonomy = \''. $this->coauthor_taxonomy.'\' AND '. $wpdb->term_taxonomy .'.term_id = \''. $current_coauthor_term->term_id .'\'';
					$this->having_terms .= ' ' . $wpdb->term_taxonomy .'.term_id = \''. $current_coauthor_term->term_id .'\' OR ';
					
					$currentUser = get_current_user_id();
					if (isset($_GET['author_name']) && $_GET['author_name']) {
						$user = get_user_by('login', $_GET['author_name']);
						
						if ($user && $user->ID) {
							$currentUser = $user->ID;
						}
					} else if (is_author()) {
						$currentUser = 'user_' . get_the_author_meta('ID');
					}
					$where = preg_replace( '/(\b(?:' . $wpdb->posts . '\.)?post_author\s*=\s*(' . $currentUser . '))/', $current_user_query, $where, -1 ); #' . $wpdb->postmeta . '.meta_id IS NOT NULL AND
```

**Comment by TheCrowned** [comment] 2018-08-27 07:04
Duplicate of #573.

**Closed** 2018-10-24 02:00 UTC
