### ISSUE TITLE
rest_forbidden as an second author

### ISSUE THREAD

**Issue by lukaszange** [Automattic/Co-Authors-Plus#754] opened 2021-03-09 00:03 UTC
When I try to edit a post with an assigned second author, I get the error message "rest_forbidden":

`code: "rest_forbidden"
data: Object { status: 403 }
​message: "Sorry, you are not allowed to do that."`

I have already isolated the plugin (deactivated all other plugins one after the other and also for themes), but just can't find a problem. Anyone an idea?

**Comment by rebeccahum** [comment] 2021-03-09 15:15
@lukaszange Is this reproducible on a local environment? If so, can you please provide the steps? Thanks!

**Comment by lukaszange** [comment] 2021-03-09 15:37
Here's a video of the steps if that clarifies the problem

https://user-images.githubusercontent.com/42523323/110496290-9fb95c00-80f5-11eb-86f5-3a18fa518e72.mov

**Comment by rebeccahum** [comment] 2021-03-09 16:39
You could try running `wp co-authors-plus create-terms-for-posts` and see if that fixes the post terms if you suspect that is the issue. Since you are unable to reproduce on an empty WP install, could it be theme related?

Best way forward is some reproducible steps on an empty WP install.

**Comment by lukaszange** [comment] 2021-03-10 17:47
And that exactly doesn't work for me on multiple instances.
For me, the mistake is with both the author and the contributor - and that's with a draft, not a published post. Couldn't you reproduce that?

**Comment by lukaszange** [comment] 2021-03-10 17:53
Here is an example on a completely new installation.

https://user-images.githubusercontent.com/42523323/110674117-dc5a8580-81d1-11eb-8478-e3f24547a3f1.mov

**Comment by rebeccahum** [comment] 2021-03-10 18:00
Hi @lukaszange, I've been unable to reproduce on several tries on a single site installation using twentytwentyone on WordPress 5.7. Can you please provide us with further details on your environment (custom theme? single site or multi-site?)?

**Comment by lukaszange** [comment] 2021-03-10 18:18
- WP: 5.7
- Single-Site
- several Themes (Custom; Twenty Nineteen 2.0; Twenty Twenty-One 1.2; Twenty Twenty 1.7)
- PHP: 7.4.14 & 7.4.15
- Apache & nginx
- MySQL: 5.7.29 & 5.7.30-log

**Comment by lukaszange** [comment] 2021-03-10 18:25
can also create an instance for you on my server and send you the relevant access data by email, if you want @rebeccahum?

**Comment by rebeccahum** [comment] 2021-03-10 18:26
Thanks, @lukaszange. That won't be necessary — it would be best to be able to reliably reproduce it on a clean WP install locally without requiring any server access.

**Comment by lukaszange** [comment] 2021-03-10 18:59
Here is a completely new installation on a new system (local environment) with PHP 8.0 - I don't quite understand why you can't replicate the whole thing? 

https://user-images.githubusercontent.com/42523323/110682157-ecc32e00-81da-11eb-86bb-15af0c6c4221.mp4

**Comment by rebeccahum** [comment] 2021-03-10 22:58
Looping you in @nielslange to see if you can reproduce it.

**Comment by nielslange** [comment] 2021-03-12 12:21
While the problem is clearly related to permission settings within the REST API, I'm still investigating if it can be addressed within the plugin or if solving this problem requires an adjustment within core. That said, these are my findings so far.

## Admin

<table>
	<tr>
		<th></th>
		<th>Block editor</th>
		<th>Classic editor</th>
	</tr>
	<tr>
		<td>Admin can edit drafted post</td>
		<td align="center">✅</td>
		<td align="center">✅</td>
	</tr>
	<tr>
		<td>Admin can edit pending post</td>
		<td align="center">✅</td>
		<td align="center">✅</td>
	</tr>
	<tr>
		<td>Admin can edit scheduled post</td>
		<td align="center">✅</td>
		<td align="center">✅</td>
	</tr>
	<tr>
		<td>Admin can edit published post</td>
		<td align="center">✅</td>
		<td align="center">✅</td>
	</tr>
	<tr>
		<td>Admin can edit private post</td>
		<td align="center">✅</td>
		<td align="center">✅</td>
	</tr>
	<tr>
		<td>Admin can edit protected post</td>
		<td align="center">✅</td>
		<td align="center">✅</td>
	</tr>
</table>

## Editor

<table>
	<tr>
		<th></th>
		<th>Block editor</th>
		<th>Classic editor</th>
	</tr>
	<tr>
		<td>Editor cannot edit drafted post</td>
		<td align="center">✅</td>
		<td align="center">✅</td>
	</tr>
	<tr>
		<td>Editor can edit pending post</td>
		<td align="center">✅</td>
		<td align="center">✅</td>
	</tr>
	<tr>
		<td>Editor can edit scheduled post</td>
		<td align="center">✅</td>
		<td align="center">✅</td>
	</tr>
	<tr>
		<td>Editor can edit published post</td>
		<td align="center">✅</td>
		<td align="center">✅</td>
	</tr>
	<tr>
		<td>Editor can edit private post</td>
		<td align="center">✅</td>
		<td align="center">✅</td>
	</tr>
	<tr>
		<td>Editor can edit protected post</td>
		<td align="center">✅</td>
		<td align="center">✅</td>
	</tr>
</table>

## Author

<table>
	<tr>
		<th></th>
		<th>Block editor</th>
		<th>Classic editor</th>
	</tr>
	<tr>
		<td>Author can edit drafted post</td>
		<td align="center">❌</td>
		<td align="center">✅</td>
	</tr>
	<tr>
		<td>Author can edit pending post</td>
		<td align="center">❌</td>
		<td align="center">✅</td>
	</tr>
	<tr>
		<td>Author can edit scheduled post</td>
		<td align="center">❌</td>
		<td align="center">✅</td>
	</tr>
	<tr>
		<td>Author can edit published post</td>
		<td align="center">✅</td>
		<td align="center">✅</td>
	</tr>
	<tr>
		<td>Author can edit private post</td>
		<td align="center">❌</td>
		<td align="center">❌</td>
	</tr>
	<tr>
		<td>Author can edit protected post</td>
		<td align="center">✅</td>
		<td align="center">✅</td>
	</tr>
</table>

## Contributor

<table>
	<tr>
		<th></th>
		<th>Block editor</th>
		<th>Classic editor</th>
	</tr>
	<tr>
		<td>Contributor can edit drafted post</td>
		<td align="center">❌</td>
		<td align="center">✅</td>
	</tr>
	<tr>
		<td>Contributor can edit pending post</td>
		<td align="center">❌</td>
		<td align="center">✅</td>
	</tr>
	<tr>
		<td>Contributor can edit scheduled post</td>
		<td align="center">❌</td>
		<td align="center">✅</td>
	</tr>
	<tr>
		<td>Contributor can edit published post</td>
		<td align="center">✅</td>
		<td align="center">✅</td>
	</tr>
	<tr>
		<td>Contributor can edit private post</td>
		<td align="center">❌</td>
		<td align="center">❌</td>
	</tr>
	<tr>
		<td>Contributor can edit protected post</td>
		<td align="center">✅</td>
		<td align="center">✅</td>
	</tr>
</table>

**Comment by htdat** [comment] 2021-03-21 10:03
## My debugging steps 

I started with @nielslange's excellent finding: 

> I’m currently looking into https://github.com/Automattic/Co-Authors-Plus/issues/754 and the user reported seeing the error message code: `"rest_forbidden" data: Object { status: 403 } message: "Sorry, you are not allowed to do that."`. 
> I found out that this problem only appears for contributors and authors when trying to access a drafted, pending or scheduled post to which they have been added as co-author.
> I traced back to problem to 
> 
> https://github.com/WordPress/WordPress/blob/471fc1e913869015ddcfa9446ef5c8f6c9752974/wp-includes/rest-api/class-wp-rest-server.php#L1108-L1116
> 
> Checking the value of $permission, I receive a `true` when looking up the default WordPress route (in my case: http://localhost:10147/wp-admin/post.php?post=1&action=edit) and `false`  when looking up the REST API route (in my case: http://localhost:10147/wp-json/wp/v2/posts/1?context=edit&_locale=user).

Line 1106 decides the value of $permission: 

```php 
			$permission = call_user_func( $handler['permission_callback'], $request );
``` 

I then turned into looking at the `$handler['permission_callback']` for this REST API request `GET /wp/v2/posts/:id`. 
This route is registered in [class WP_REST_Posts_Controller](https://github.com/WordPress/WordPress/blob/52679edbffe1a28cf7fce54ab2077f299c8cf27e/wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php#L89-L104). 

I then focused on the `get_item_permissions_check()` method of this class - [code ref](https://github.com/WordPress/WordPress/blob/52679edbffe1a28cf7fce54ab2077f299c8cf27e/wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php#L421-L456).

After many trial-and-error tests, I could find out the permission check fails at checking the read permission - lines 451-453: 

```
		if ( $post ) {
			return $this->check_read_permission( $post );
		}
``` 

(Hint: I tried to `return` before each of `if` conditions in this `get_item_permissions_check()` method). 

I continued moving to `check_read_permission()` method - [code ref](https://github.com/WordPress/WordPress/blob/52679edbffe1a28cf7fce54ab2077f299c8cf27e/wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php#L1537). And here is the part of this check returns `false`: 

```php
		// Is the post readable?
		if ( 'publish' === $post->post_status || current_user_can( 'read_post', $post->ID ) ) {
			return true;
		}
``` 

In this case, it's a `draft` post so the main issue is the latter condition that checks if this user can `read_post` this specific `$post->ID`. 

This also explains why co-authors can access `publish` posts for editing. 

## Fix 

Adding `read_post` cap for co-authors, who are assigned to a specific post, fixes this issue. 
PR #757

**Closed** 2021-03-26 16:48 UTC
Labels: confirmed-bug, needs-investigation

**Comment by nielslange** [comment] 2021-03-28 02:37
@lukaszange The problem, that you reported, had been fixed and a new version of the plug-in had been released. Once you update the plugin on your end, it should work as expected.

**Comment by lukaszange** [comment] 2021-03-28 10:17
Thanks @htdat, @nielslange & @rebeccahum for the perfect job here! :)
