### ISSUE TITLE
Changing sort order of coauthors broken in WordPress ^4.7.x

### ISSUE THREAD

**Issue by dsifford** [Automattic/Co-Authors-Plus#390] opened 2016-12-10 03:05 UTC
Hello there,

It appears that ever since the update to WordPress 4.7, changing sort order of coauthors no longer works properly.

I confirmed this on a clean install of WordPress with only co-authors-plus installed. It's most definitely an issue with this plugin.

Happy to help if needed. Thanks so much.

**Comment by blackwood** [comment] 2016-12-12 21:32
Indeed, can replicate. However, changing line 17 in `get_coauthors` in the file `template-tags.php` from:

     $coauthor_terms = get_the_terms( $post_id, $coauthors_plus->coauthor_taxonomy );

to: 

    $coauthor_terms = wp_get_post_terms( $post_id, $coauthors_plus->coauthor_taxonomy, array( 
      'orderby' => 'term_order', 
    ) );

...fixes the issue for me.

The untested theory we have over here is that the default args provided by `wp_get_object_terms` could have changed in 4.7, which is how `get_the_terms` updates the cache if there's no cached terms available -- so whenever `get_coauthors` is called, it ignores the custom `term_order`, using `name` instead.

**Comment by blackwood** [comment] 2016-12-12 21:33
...but it could be something else entirely. It would definitely be great to get the plugin author's input here.

**Comment by blackwood** [comment] 2016-12-12 21:34
#392 and #391 look like they address the same issue?

**Comment by dsifford** [comment] 2016-12-12 22:10
Thanks for the comments @blackwood -- I'll give your fix a whirl for the time being while waiting for the maintainers' input on this 😄

**Comment by dsifford** [comment] 2016-12-12 22:17
@blackwood Your fix isn't doing the trick here for me. Hmm.. Looks like the two open PRs involve clearing object cache?

Both PRs break the build so I'm curious what negative implications doing it @mslinnea's way has (if any?)

**Comment by mslinnea** [comment] 2016-12-12 23:16
Thanks for linking to my PRs.  I don't know what's up with Travis, as the errors seem unrelated to my code changes.

I tried @blackwood's fix and it does work for me, but `wp_get_post_terms` is [listed as an uncached function](https://vip.wordpress.com/documentation/caching/uncached-functions/), which is why I steered clear of using it.

**Comment by dsifford** [comment] 2016-12-12 23:24
@mslinnea Interesting. I wasn't aware of the cached/uncached functions. Thanks for the resource!

Also, perhaps @blackwood's fix will work for me... I SSH'ed into the server and made the change extremely quickly with vim so chances are I could have made a typo! I'll try it again in a few.

**Comment by blackwood** [comment] 2016-12-13 14:59
It'd be great if you could pass args along with `get_the_terms` so that it would bust the cache and reorder or set the cache with your required `$args`... but that'd be more of a core issue.

@mslinnea -- I really like the idea in #391, setting and clearing the cache manually on save/delete.

**Comment by dsifford** [comment] 2016-12-13 21:35
Sorry for the delay. @blackwood _does_ work for me. Must have been a typo last time.

**Comment by philipjohn** [comment] 2016-12-14 13:17
There were [some changes](https://core.trac.wordpress.org/changeset/38667) to `wp_get_object_terms()` in 4.7 that look related to `WP_Term_Query`.

I've reproduced this myself and I'm just checking out the two PRs.

**Comment by aous77** [comment] 2017-02-14 16:38
Hi,
is there a fix for this issue?

**Comment by AustinBrister** [comment] 2017-02-14 17:05
Yes. Look at Blackwood's comment.

**Comment by aous77** [comment] 2017-02-14 17:16
this is great!
do we know when will it get pushed to [wordpress repo](https://wordpress.org/plugins/co-authors-plus/changelog/)?

**Closed** 2017-03-11 17:39 UTC
Labels: confirmed-bug, Priority::High

**Comment by benlk** [comment] 2017-03-13 19:54
The merged fix was ultimately https://github.com/Automattic/Co-Authors-Plus/pull/391, and since this issue is in the 3.5 milestone, https://github.com/Automattic/Co-Authors-Plus/milestone/20, it probably won't get released until August 31, 2017.

**Comment by ckeeney** [comment] 2017-06-29 18:33
Is there any chance of getting this released before August 31?  It seems a bit silly for a fix to such a widely discussed bug to sit in master unreleased for several months.

**Comment by benlk** [comment] 2017-08-29 18:54
The 3.5 milestone was pushed to February 2018, but this issue is no longer in 3.5. #406 was merged to master on March 20, and version 3.2 contained these ordering fixes: https://github.com/Automattic/Co-Authors-Plus/releases/tag/3.2.2
