### ISSUE TITLE
Error when trying to assign Guest Author

### ISSUE THREAD

**Issue by danoc** [Automattic/Co-Authors-Plus#155] opened 2013-12-16 01:32 UTC
One of our writers was having trouble adding himself to a post. He would add his name, and hit save, but it wouldn't save the change.

I looked into it and it turns out he had a guest account that was mapped to his user account (no idea how/why/if he did this) and only the Guest Account appeared in the auto-complete.

I was able to fix it by deleting his guest account, moving his posts to his actual account, and then changing the author of that post.

I'm not sure why he wasn't able to assign the post to his guest account (not that he wanted to), but it would be awesome if there was a JavaScript alert instead of a silent error.

**Comment by rebeccahum** [comment] 2017-07-05 04:02
I don't think this issue is valid anymore because in `wp-admin/users.php`, there is no more "Create Profile" button due to UX changes in the plugin.

Closing this issue.

**Comment by trepmal** [comment] 2017-07-06 05:00
The "Create Profile" link can be shown by using the `coauthors_show_create_profile_user_link` filter. (This changed in v3.1) e.g.

```
add_filter( 'coauthors_show_create_profile_user_link', '__return_true' );
```

@rebeccahum, can you check if the issue is still valid?

**Comment by rebeccahum** [comment] 2017-07-06 05:33
@trepmal just enabled the filter and tested this.  I am able to add a guest author account to a post created from a user via "Update" or "Publish" .

**Closed** 2017-07-06 05:44 UTC
Labels: needs-investigation, Priority::Medium
