### ISSUE TITLE
When using with WPML, some authors don't show up in results depending on language

### ISSUE THREAD

**Issue by bonakor** [Automattic/Co-Authors-Plus#800] opened 2021-06-03 09:07 UTC
Hello,

I'm using CoauthorPlus in conjunction with WPML. 

Depending on the language, some authors won't show up in results, yet they're queryable via the classic Author box in Gutenberg.
For instance, author A will show up in results when the post is in English, but he won't show up when the post is in French.

Is there something I can do, please?

I'm using WPML latest version, same for WP and Co Author Plus.

**Comment by bonakor** [comment] 2021-06-11 08:12
If needed, I can give you access to a staging version a the website

**Comment by rebeccahum** [comment] 2021-06-11 17:10
If you can provide steps on reproducing on a local install, that would be splendid!

**Comment by bonakor** [comment] 2021-06-14 12:48
Hi.

No problem, I can. But I think I'd need to transmit the database (I can, but in private)

I have French and english configured on the website.

Whatever the theme, the bug still occurs.

Lets say, I want Simon to be author of a post in English. No problem, I can make him an author in the Co-author field. I type his name and he's there.

But if I want Simon to be author of a post in French, when I type his name, nothing appears. It tells me "no matching author found". It's doing that whatever the post, if I'm not Simon. Simon can write posts in French or in English without issue.


When I try to use the "Gutenberg author box", on the very top of the column, it finds Simon without issue.

I tried with Wordpress default themes but the bug remains.

Do you need more informatioN,

**Comment by rebeccahum** [comment] 2021-06-14 19:23
@bonakor On a clean install, it would be great if you could provide some steps to follow with specific examples to use (in this case, author name) for reproducing, thank you!

**Comment by bonakor** [comment] 2021-06-14 21:34
Okay, I'll try to reproduce it on a clean install tomorrow

**Comment by bonakor** [comment] 2021-06-15 17:13
Okay, I found the issue. It's because in WPML, "translating the author taxonomy" was allowed. If I deactivate this, it's working again.

**Comment by rebeccahum** [comment] 2021-06-16 00:34
Cool, sounds like a conflict from WPML. I'll close this out since it's not CAP-specific.

**Closed by rebeccahum** 2021-06-16 00:34 UTC
Labels: needs-investigation
