### ISSUE TITLE
Co-authors should be able to see revisions

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/Co-Authors-Plus#196] opened 2014-04-01 00:58 UTC
According to a user in the forums, [they aren't able to](https://wordpress.org/support/topic/co-authors-cannot-work-with-revisions).

**Comment by castlehouse** [comment] 2016-01-06 20:35
@danielbachhuber were you able to reproduce this?  I've tried with a few combination but can't seem to do so

**Comment by danielbachhuber** [comment] 2016-01-06 20:41
I don't recall, sorry.

**Comment by castlehouse** [comment] 2016-01-07 18:41
After another pass at this I have managed to reproduce.  When it happens the link to revisions doesn't get set in the publish box

**Comment by castlehouse** [comment] 2016-02-15 21:07
The issues in #237 mean there is no easy way to achieve this without additional database queries due to the way permissions tie with revisions.

Until there is a better method of permission checking with high numbers of child posts this is a #wontfix

**Closed by castlehouse** 2016-02-15 21:07 UTC
Labels: bug
